Sep 15, formatting id to class and spacing
Nicolebt28/nicoletanner.me pull request #3
Opened 2019-09-15 22:30 UTC by Nicolebt28

-fixed id to class
-fixed indenting spaces

2019-09-15 22:40 UTC, cory-tanner requested changes

2019-09-15 22:40 UTC, Ctannerweb commented on index.html
> +  <h1 class= "welcome"> Hello! My name is Nicole, an aspiring web deveolper and web designer.</h1>
🔥extra space `class= "foo"`

2019-09-15 22:40 UTC, Ctannerweb commented on index.html
> +<div id= "projects_section" class= "projects_section">
🔥extra space `class= "foo"`

2019-09-15 22:40 UTC, Ctannerweb commented on index.html
> +  <p class= "project_text" class= "project_opener">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 15
🔥extra space `class= "foo"`

2019-09-15 22:40 UTC, Ctannerweb commented on index.html
> +  <h2 class= "checklist"> To-Do List</h2>
🔥extra space `class= "foo"`

2019-09-15 22:40 UTC, Ctannerweb commented on index.html
> +  <h2 class= "recipe">Cooky Cookie's Recipe Card</h2>
🔥extra space `class= "foo"`

2019-09-15 22:40 UTC, Ctannerweb commented on index.html
> +  <h2 class= "timer"> Tabata Timer</h2>
🔥extra space `class= "foo"`

2019-09-15 22:40 UTC, Ctannerweb commented on index.html
> +<div id= "contact" class= "contact">
🔥extra space `class= "foo"`

2019-09-15 22:40 UTC, Ctannerweb commented on index.html
> +
🔥 Extra lines

2019-09-15 22:40 UTC, Ctannerweb commented on style.css
> +main {
Apply this with a class, avoid styling HTML elements via the element name at all costs

2019-09-15 22:40 UTC, Ctannerweb commented on style.css
> +nav{
Same as what I said above

2019-09-15 22:40 UTC, Ctannerweb commented on style.css
> +li {
Same as what I said above

2019-09-15 22:40 UTC, Ctannerweb commented on style.css
> +a {
Same as what I said above

2019-09-15 22:40 UTC, Ctannerweb commented on style.css
> +a.visited{
Same as what I said above

2019-09-15 22:40 UTC, Ctannerweb commented on style.css
> +.projects_section{
Add a space between the class name and `{`

2019-09-15 22:40 UTC, Ctannerweb commented on style.css
> +  color: #b33939;
Apply colors with CSS custom properties. `var(--foo-color)`. https://developer.mozilla.org/en-US/docs/Web/CSS/--*

2019-09-15 22:40 UTC, Ctannerweb commented on index.html
> +<main id="home">
Has an ID :(

2019-09-15 22:40 UTC, Ctannerweb commented on index.html
> +  <h2 class="project_opener"> Here are some sites I've created...</h2>
use CSS ellipsis https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

2019-09-15 22:40 UTC, Ctannerweb commented on index.html
> +  <p class= "project_text" class= "project_opener">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 15
You have 2 classes?

2019-09-15 22:40 UTC, Ctannerweb commented on index.html
> +  <h2>Email: email@web.com</h2>
Email uses an email link

2019-09-15 22:40 UTC, Ctannerweb commented on index.html
> +  <h2>Phone: 888-888-8888</h2>
leave your phone number off the site. but also use a tele link instead of a heading

2019-09-16 17:35 UTC, Ctannerweb commented
Next step is to fix these changes and push a second commit to the branch. That commit will show here in this PR @Nicolebt28

2019-09-20 21:40 UTC, Ctannerweb commented
Still has updates that need to be made relative to using classes to apply styling.

2019-09-24 02:25 UTC, Nicolebt28 commented
can you give me an example of 1 or 2 elements you would change to use
classes in the way you're describing?

On Fri, Sep 20, 2019 at 5:40 PM Cory Tanner <notifications@github.com>
wrote:

> Still has updates that need to be made relative to using classes to apply
> styling.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Nicolebt28/nicoletanner.me/pull/3?email_source=notifications&email_token=AMLV2XF6QQPAW65FLXNOSODQKU7LRA5CNFSM4IW4GBHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7H6FDA#issuecomment-533717644>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMLV2XCSYVWNCE4Q5XHNFA3QKU7LRANCNFSM4IW4GBHA>
> .
>

2019-10-19 05:04 UTC, closed without merging